train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        min_gain_in_db: -2
        max_gain_in_db: 6
        p: 0.3
      - _target_: src.transforms.wav_augs.AddNoiseAug
        p: 0.52
        sample_rate: 16000
    #   - _target_: src.transforms.wav_augs.ApplyPitchShift
    #     sample_rate: 16000
      - _target_: src.transforms.wav_augs.ApplyHighPassFilter
        p: 0.2
        sample_rate: 16000
        min_cutoff_freq: 500
        max_cutoff_freq: 1000
      - _target_: src.transforms.wav_augs.ApplyLowPassFilter
        p: 0.2
        sample_rate: 16000
        min_cutoff_freq: 800
        max_cutoff_freq: 1500


inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
